import Head from "next/head";
import Header2 from "../components/UI/Header2";
import Footer2 from "../components/UI/Footer2";
import HomeSpecial from "../components/Home/HomeSpecial";
import HomeMain from "../components/Home/HomeMain";
import HomeNew from "../components/Home/HomeNew";
import HomeRec from "../components/Home/HomeRec";
import GetInTouch from "../components/UI/GetInTouch";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import DATA from "../data.json";
import BookData from "../data2.json"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeMain />
      <HomeSpecial />
      <HomeNew data={DATA} />
      <HomeRec data={DATA} />
      <GetInTouch />
    </>
  );
}
Home.getLayout = (page) => (
  <>
    <Header2 placeholder="SEARCH HERE" data={BookData}/>
    {page}
    <Footer2 />
  </>
);
